# Generated by Django 5.0.7 on 2024-11-16 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=50)),
                ('whatsapp_no', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=255)),
                ('vat_no', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
