# Generated by Django 5.0.7 on 2024-11-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
