# Generated by Django 5.0.7 on 2024-11-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userinfo_id_alter_userinfo_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_no',
            field=models.CharField(max_length=50),
        ),
    ]
